---
title: "Methodology"
author: "Milan Kilibarda, Dragutin Protic"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: word_document
---


This document provides the methodlogy for the spatialization of pollutation inventory for the territory of Serbia. The methodology differs according to whether or not sources are listed or according to the type of the sources. 
 
 
```{r include = TRUE, echo = FALSE, results = 'hide', warning = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(ggpubr)
library(ggfortify)
library(here)
library(knitr)
library(kableExtra)
library(DT)
```


# Auxiliary Data to be used:

 - The road network, including 1A, 2A, 1B and 2B road category [^1], 
 - Data of the Mean Daily Trafic for one Year (MDTY) obtained from ~400 automatic Vehicle Counting Devices (VCD), spreaded over the whole territory of Serbia, on three different road category (1A, 2A and 1B) [^1],
 - Number of vehicles registered in each municipality of the Serbia for the year 2015 [^2].
 - The map of Serbia with municipalities [^3]
 - Road network within the urban areas [^4]
 - Corine Land Cover for the territory of Serbia [^5]
 - Network of rails[^4]
 - Database of the Serbian Business Registers Agency [^6]
 - National inventory of agriculture [^2]
 - Official annual report from the public company "Toplane Srbije". [^7]
 
 [^1]: Source: Public Enterprise “Roads of Serbia”
 [^2]: Source: Statistical Office of the Republic of Serbia.
 [^3]: Source: GADM, the Database of Global Administrative Areas.
 [^4]: Source: Open Street Maps
 [^5]: Source: Corine Land Cover
 [^6]: Source: The Serbian Business Registers Agency
 [^7]: Source: Official annual report of the public company "Toplane Srbije"



# 1A1 - Energy - Solved

- **Methodology:** Considering that this category contains only the points sources and that the Total inventory match the Spatialized inventory, spatial dissagregation was done by spatially overlaying of the 5x5km cells grid with the spatial layer of the sources from each category.   

# 1B - Fugitive emissions - Solved

### 1B1a - Fugitive emissions from solid fuels

- **Problem:** The sources do not exist

- **Methodology:** Spatial Locations of coal mines are identified, and then used for identification of the polygons within the CLC 131 class (Mines). Then,  the Total inventory were dissagregated to the 5x5km cells proportionally to the areas of the identified polygons of coal mines that lie within the each cell.  


### 1B2ai - Fugitive emissions from liquid fuels : Exploration, production, transport.

- **Problem:** The sources do not exist

- **Methodology:** Total inventory was spatialized on 5x5km cells proportionally to the length of the roads (including road from IA, IIA and IB road categories)  multiplied by corresponding average road activity (average daily number of vehicles for one year). This information was previously calclulated for the purpose of the spatialization of 1A3-Transport Category. 


### 1B2av - Fugitive emissions from liquid fuels : Distribution of oil products.

- **Problem:** The sources do not exist

- **Methodology:** Total inventory was spatialized on urban areas of the each municipality, proportionally to the number of vehicles registered in each municipality. The municipalities with the number of registered vehicles bellow the 100 were not considered. By doing this, it has adopted as the thesholds for a service station to be plausible. Number of registered vehicles were taken from the official database of the Statistical Office of the Republic of Serbia.

### 1B2b - Fugitive emissions from natural gas : Exploration, production, transport.

- **Problem:** The sources do not exist

- **Methodology:** Total inventory was spatialized on 5x5km cells proportionally to the length of the roads (including road from IA, IIA and IB road categories)  multiplied by corresponding average road activity (average daily number of vehicles for one year). These informations were previously calclulated for the purpose of the spatialization of 1A3-Transport Category. 

# 1A3 - Transport

### 1A3ai (i) - International aviation LTO (civil) - Solved 

- **Problem:** The sources do not exist.

- **Methodology:** Total inventory was spatially allocated to the point sources (Airports) according to the official data from the Serbian Business Registers Agency.

### 1A3aii (i) - Domestic aviation LTO (civil) - Solved 

- **Problem:** The sources do not exist.

- **Methodology:** Total inventory was spatially allocated to the point sources (Airports) according to the official data from the Serbian Business Registers Agency.


### Road transport - Solved

- **Problem:** The sources do not exist.

The proposed methodology was applied on the road transport subcategories that includes the urban/rural/highway inventory separately:

- 1A3bi - Road transport: Light-duty vehicles
- 1A3bii - Road transport: Heavy-duty vehicles
- 1A3biii - Road transport: Buses & Coaches
- 1A3biv - Road transport: Mopeds & motorcycles
- 1A3bv - Road transport: Gasoline evaporation

#### Steps:

**Rural inventory**

 1. Spatial classification of the whole Territory of Serbia into urban and rural areas based on Corine Land Cover data.
 2. For each road section (including the sections with VCDs) MDTY was calculated as weighted mean of 5 neighbouring road section with VCDs (if exist within the radius of 50km.). Weights were created as inverse distances between the lines (road sections). If target road section intersect with another road section that has VCD, the distance between them is set to be close to zero in order to avoid dividing by zero. By doing so, the main influence in calculating the weighted mean belongs to the sections with VCDs from the very close vicinity. This interpolation was done within the each road category where VCD exist (IA, IIA and IB). In this way, the vehicle activity for each road will be estimated.
 3. Based on these estimates, total rural inventory for each vehicle category will be spatially dissagregated into the 5x5km cells propotionally, by taking the estimated MDTY and the lengths of corresponding road sections that lie within the cell into account.
 

**Urban inventory**
 1. First, total inventory pollution was spatially dissagregated proportionally to the urban areas of each municipality based on the number of the vehicles registered in each municipality. For this purpose, data from the official database of the Statistical Office of the Republic of Serbia was used.
 2. Next, the estimated emissions in urban areas were further spatialized into 5x5km cells based on the the lenght of the roads in urban areas that lie in each cell. For this purpose, road network in urban areas was generated by using the Open Street Map data and CLC class for urban areas.
 
**Highway inventory**
 
 - Total inventory for highway transport will be spatially dissagregated based lenght of the corresponding highway section that lie in each cell multiplied by the estimated MDTY values The MDTY values are estimated according to the methodology given above. 
    
**Total inventory**
 
 - Total air pollution from the road transport in each cell will be estimated as the sum of estimated/spatialized pollution for rural, urban and highway transport for each cell.     


### 1A3vi - Road transport: Automobile tyre and brake wear - Solved

- **Problem:** The sources do not exist.

- **Methodology:** Total inventory will be spatially dissagregated into the 5x5km cells propotionally, based on the length of roads that lie within the cell multiplied by corresponding MDTY.

### 1A3vii - Road transport: Automobile road abrasion - Solved

- **Problem:** The sources do not exist.

- **Methodology:** Total inventory will be spatially dissagregated into the 5x5km cells propotionally, based on the length of roads that lie within the cell multiplied by corresponding MDTY.

### 1A3c - Railways - Solved

- **Problem:** The sources do not exist.

- **Methodology:** Total inventory will be spatially dissagregated into the 5x5km cells propotionally to the lengths of the acitve rails that lie within the cell.

### 1A3dii - National navigation (shipping) - Solved

- **Problem:** The sources do not exist.

- **Methodology:** Total inventory will be spatially dissagregated into the 5x5km cells propotionally area of the navigable rivers that lie within the cell.



# 1A4 - Residential, Tertiary and Agriculture/Forestry sector - Solved


### 1A4ai - Commercial/Institutional: Stationary Combustion

- **Problem:** The sources do not exist.

- **Methodology:** Total inventory was spatialized on the urban areas in each municipality, proportionally to the total heating area of the residental houses as well as, the institutional and commercial buildings, connected to the remote heating system. This information is available via official report of the public company "Toplane Srbije".

### 1A4bi - Residential : Stationary combustion - Solved

- **Problem:** The sources do not exist.

- **Methodology:** Total inventory was spatialized on the urban areas in each municipality, proportionally to the number of the residental houses that are not connected to the remote heating system. Having the total number of houses as well as the number of houses connected to the remote heating system, number of residental houses that are not connected to the remote heating system is given as difference between two numbers. For the areas without remote heating plants, number of residental houses is available from the official database of the Statistical Office of the Republic of Serbia.


### 1A4ci - Agriculture/Forestry/Fishing: Stationary combustion - Solved

- **Problem:** The sources do not exist.

- **Methodology:** Total inventory was spatialized on the urban areas of each municipality, proportionally to the total investment in  Agriculture/Forestry/Fishing. This information is available from the official database of the Statistical Office of the Republic of Serbia. **ili po povrsini poljoprivrednog zemiljista iz korine**


### 1A4cii - Agriculture/Forestry/Fishing: Off-road vehicles and other machinery - Solved

- **Problem:** The sources do not exist.

- **Methodology:** Total inventory was spatialized on the rural areas (other than urban) of each municipality, proportionally to the total number of registered industrial vehicles. This information is available from the official database of the Statistical Office of the Republic of Serbia.



# 1A2-2 - Industry - Solved

- **Methodology:** Considering that subcategories (listed bellow) contains only the points sources and that the Total inventory match the Spatialized inventory, spatial dissagregation was done by spatially overlaying of the 5x5km cells grid with the spatial layer of the sources from each category.

- 1A2a / 2C1 - Iron and Steel
- 1A2b - Non-ferrous metals
- 1A2c - Chemicals
- 1A2d - Pulp, paper and print
- 1A2e - Food, beverages and tobacco
- 1A2f - Non-metallic minerals


### 1A2g - Other Industry - Solved

- **Problem:** The difference between Total inventory and Total spatialized is significant

- **Methodology:** Some of the point-sources are listed, but the difference to Total inventory is too large. Therefore, the rest of the Total inventory will be spatially allocated to the industrial zones which do not match spatially with point sources of the other subcategory from 1A2 category (Industry). For this purpose, the industrial zones will be extracted from the Corine Land Cover data [^5]. Spatial allocation will be conducted proportionally, according the the areas of the industrial zones. After that, the total inventory of each industrial zone will be further allocated to 5x5km cells propotionally according the the areas of the industrial zones that lies in each cell.

### 1A2g - Auto-production - Solved

- **Problem:** The sources do not exist.

- **Methodology:** Total of 37 factories that are included in automobile production industry are identified and geo-located. Spatial allocation of the Total inventory was conducted proportionally to the number of employs. This number was taken from the the official database of the The Serbian Business Registers Agency [^6].

### 1A2g - Mobile combustion in manufacturing industries and construction - Solved

- **Problem:** The sources do not exist.

- **Methodology:** Total inventory from this sub-category will be spatially allocated to the areas that represents the industrial zones and construction sites. For thus purpose, the industrial zones and construction sites will be extracted from the Corine Land Cover data. The distribution will be conducted proportionally according to the areas of the industrial zones and construction sites. After that, the total inventory of each industrial zone will be further allocated to 5x5km cells propotionally according the areas of the industrial zones that lies in each cell.


# 2-Other processes (Industrial Processes and Product Uses)

### 2S5a - Quarrying and mining of minerals other than coal - Solved

- **Problem:** The difference between Total inventory and Total spatialized is significant

- **Methodology:** The difference between Total inventory and Total spatialized inventory was spatially allocated to the identified locations of the mines of minerals (other than coals) proportionally, by taking the existing values of point sources to create weights. The larger the source, the larger portion of difference is assigned to it.  

### 2A5b - Construction and demolition - Solved

- **Problem:** The sources do not exist.

- **Methodology:**  Total inventory was spatialized on urban areas proportionally to the population of the corresponding municipality.

### 2A5c - Storage, handling and transport of mineral products - Solved

- **Problem:** The sources do not exist.

- **Methodology:** Previously locations of mines were utilized to identify the major roads that intersect in the close vicinity of the each mine. Then, Total inventory was spatially allocated to the 5x5km cells proportionally to the length of selected roads that lie within each cell. 

### 2D2G - Solvents (use) - Solved

- **2D3b - Road paving with asphalt**
- **2D3c - Asphalt roofing**
- **2D3d - Coating application**

-- **Problem:** The sources do not exist.

-- **Methodology:** Total inventory was spatialized on 5x5km cells proportionally to the length of the roads (including road from IA, IIA and IB road categories).

- **2D3g - Chemical products**
- **2D3i - Other solvent and product use**
- **2D3a - Domestic solvent use including fungicides**
- **2D3e - Degreasing**
- **2D3f - Dry cleaning**
- **2D3h - Printing**

-- **Problem:** The sources do not exist.

-- **Methodology:** Total inventory for those sub-categories were spatialized on the urban areas proportionally to the population of the corresponding municipality. It was calculated by using the data from the official database of the Statistical Office of the Republic of Serbia as well as the CLC class for urban zones.

### 2l - Wood processing - Solved

- **Problem:** The sources do not exist.

- **Methodology:** The official database of the Statistical Office of the Republic of Serbia provide the information about the total volume of the industrial woods in each municipality in Serbia. These information was geographically assign to the corresponding geometry and then to the corresponding urban areas, by using the CLC class for urban areas. After that, spatial allocation was done proportioanally the urban areas multiplied by the total volume of the industrial wood that lie within the each cell.

# 3 - Agriculture - Partially solved

### 3B3 - Manure management - Swine - Solved 

- **Problem:** Total inventory does not match the Spatialized inventory.

- **Methodology:** The difference between Total inventory and Total spatialized inventory was spatially allocated to the identified locations of the existing sources proportionally, by taking the existing values of point sources to create weights. The larger the source, the larger portion of difference is assigned to it.

### 3B4gi &  3B4gii - Laying hens & Broilers - Solved


 - **Problem:** The Total inventory does not match the Spatialized inventory.

 - **Methodology:** The difference between Total inventory and Total spatialized inventory was spatially allocated to the identified locations of the existing sources proportionally, by taking the existing values of point sources to create weights. The larger the source, the larger portion of difference is assigned to it.
 
 
### Other agriculture - Not resolved

- **Problem:** The sources do not exist.

 - **Methodology:** Considering that the sources for the other subcategories (3B1a, 3B1b, 3B2, 3B4a, 3B4d, 3B4e, 3B4f, 3B4giii, 3B4giv, 3B4h, 3Da1, 3Da2a, 3Da2b, 3Da2c, 3Da3, 3Da4, 3Db, 3Dc, 3Dd, 3De, 3Df, 3F) migth be resolved by using the data from the National inventory of agriculture database [^2] up to level of the municipalitiy areas.
 
 
# 5 - Waste - Partially resolved 
 
### 5A - Solid waste disposal - Solved
 
- **Problem:** The sources do not exist.

- **Methodology:** The Total inventory from this subcategory will be spatially allocated to the areas that represents the Solid waste disposal. For thus purpose, the dump sites will be extracted from the Corine Land Cover data (class 1.3.2 the of Corine Land Cover). Spatial allocation will be conducted proportionally, according the areas of the dump sites. After that, each portion that belongs to individual site will be further allocated to 5x5km cells propotionally according the the areas of the dump site that lies in each cell.
 
 
### 5C1bv - Cremation - Solved

- **Problem:** The sources do not exist.

- **Methodology:** The Total inventory will be spatialized on two locations where cremation happens (Belgrade and Novi Sad).


### 5D1 - Domestic wastewater handling - Solved

- **Problem:** The sources do not exist.

- **Methodology:**  Total inventory was spatialized on the urban areas in each municipality, proportionally to the total volume of the waste water released from the residential houses. This information is available via the official database of the Statistical Office of the Republic of Serbia.

### 5D2 - Industrial wastewater handling - Solved

- **Problem:** The sources do not exist.

- **Methodology:**  Total inventory is negligible.

